# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 21:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180618_0604'),
        ('accounts', '0008_auto_20180617_1440'),
        ('accounts', '0008_auto_20180612_1130'),
    ]

    operations = [
    ]
