# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-19 21:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_merge_20180619_2144'),
        ('api', '0021_ping_n'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'get_latest_by': 'created'},
        ),
        migrations.RemoveField(
            model_name='notification',
            name='status',
        ),
        migrations.AddField(
            model_name='check',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Department'),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_down',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_interval',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_list',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='escalation_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='member_allowed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='member_allowed_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='nag',
            field=models.DurationField(default=datetime.timedelta(0, 3600)),
        ),
        migrations.AddField(
            model_name='check',
            name='nag_after',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='check',
            name='nag_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='notification',
            name='error',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='channel',
            name='kind',
            field=models.CharField(choices=[(b'email', b'Email'), (b'webhook', b'Webhook'), (b'hipchat', b'HipChat'), (b'slack', b'Slack'), (b'pd', b'PagerDuty'), (b'po', b'Pushover'), (b'victorops', b'VictorOps')], max_length=20),
        ),
        migrations.AlterField(
            model_name='channel',
            name='value',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[(b'up', b'Up'), (b'down', b'Down'), (b'new', b'New'), (b'paused', b'Paused'), (b'too often', b'Too Often')], default=b'new', max_length=9),
        ),
    ]
