# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_github'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='owner',
            new_name='user',
        ),
    ]
