# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-20 23:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_auto_20180620_1951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='github',
            old_name='token',
            new_name='access_token',
        ),
        migrations.AddField(
            model_name='github',
            name='scopes',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='github',
            name='token_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
