# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 09:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0025_auto_20180620_2314'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platforms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('granted', models.BooleanField(default=False)),
                ('state', models.TextField(null=True)),
                ('code', models.TextField(null=True)),
                ('access_token', models.TextField(null=True)),
                ('token_type', models.CharField(max_length=100, null=True)),
                ('scopes', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='github',
            name='user',
        ),
        migrations.DeleteModel(
            name='Github',
        ),
    ]
