# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 17:27
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20180621_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='platforms',
            name='entities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, null=True, size=None),
        ),
    ]
