# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180619_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='member_allowed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='member_allowed_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='member_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='check',
            name='membership_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='check',
            name='status',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('new', 'New'), ('paused', 'Paused'), ('too often', 'Too Often')], default='new', max_length=9),
        ),
    ]
