# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 05:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20180607_1003'),
        ('api', '0027_auto_20180607_2141'),
    ]

    operations = [
    ]
