# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-08 12:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20180607_2141'),
        ('api', '0028_auto_20180607_1003'),
    ]

    operations = [
    ]
