# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-13 19:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20180613_1446'),
        ('api', '0029_merge_20180608_1209'),
    ]

    operations = [
    ]
