# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_merge_20180618_0552'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='member_allowed_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='check',
            name='member_allowed_id',
            field=models.IntegerField(default=0),
        ),
    ]
