# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-18 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_auto_20180618_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='check',
            name='is_alerted',
            field=models.BooleanField(default=False),
        ),
    ]
